data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/train/zh.small.txt"
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/train/en.small.txt"
  valid_data:
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/test/mt03.small.src"
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/test/mt03.small.ref0"
  bleu_valid_reference: "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/test/mt03.small.ref"
  vocabularies:
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/vocab/zh.json"
      max_n_words: 30000
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/vocab/en.json"
      max_n_words: 30000
  max_len:
    - 80
    - 80
  num_refs: 4
  eval_at_char_level: false

model_configs:
  model: DL4MT
  d_word_vec: 512
  d_model: 1024
  dropout: 0.5
  proj_share_weight: true
  bridge_type: "mlp"

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.0005
  grad_clip: 1.0
  optimizer_params: ~
  schedule_method: loss
  scheduler_configs:
    patience: 2
    min_lr: 0.00005
    scale: 0.5

training_configs:
  seed: 1234
  max_epochs: 3
  shuffle: true
  use_bucket: true
  buffer_size: 1000
  batch_size: 50
  batching_key: "samples"
  update_cycle: 1
  valid_batch_size: 20
  disp_freq: 1000
  save_freq: 1000
  num_kept_checkpoints: 1
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  bleu_valid_batch_size: 5
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 150
    beam_size: 5
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 50