data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/perceptron/workspace/nlp/tvsub/train/train-doc.zh.small"
    - "/home/perceptron/workspace/nlp/tvsub/train/train-doc.en.small"
  valid_data:
    - "/home/perceptron/workspace/nlp/tvsub/dev/dev_src-doc.small"
    - "/home/perceptron/workspace/nlp/tvsub/dev/dev_tgt-doc.small"
  bleu_valid_reference: "/home/perceptron/workspace/nlp/tvsub/dev/dev_tgt-doc.small"
  vocabularies:
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/tvsub/vocab/zh-doc.json"
      max_n_words: 30000
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/tvsub/vocab/en-doc.json"
      max_n_words: 30000
  max_len:
    - -1
    - -1
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: D2D
  enable_history_context: true
  n_layers: 2
  n_head: 2
  d_word_vec: 10
  d_model: 10
  d_inner_hid: 20
  dropout: 0.1
  proj_share_weight: true
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 20
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 40
  shuffle: true
  use_bucket: true
  batch_size: 2
  batching_key: "samples"
  update_cycle: 4
  disp_freq: 5
  save_freq: 5
  num_kept_checkpoints: 1
  loss_valid_freq: 500
  valid_batch_size: 1
  bleu_valid_freq: 500
  bleu_valid_batch_size: 1
  bleu_valid_warmup: 0
  bleu_valid_configs:
    max_steps: 150
    beam_size: 1
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 50