data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/perceptron/workspace/nlp/tvsub/train/train.zh.small"
    - "/home/perceptron/workspace/nlp/tvsub/train/train.en.small"
  valid_data:
    - "/home/perceptron/workspace/nlp/tvsub/dev/dev_src.small"
    - "/home/perceptron/workspace/nlp/tvsub/dev/dev_tgt.small"
  bleu_valid_reference: "/home/perceptron/workspace/nlp/tvsub/dev/dev_tgt.small"
  vocabularies:
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/tvsub/vocab/zh.json"
      max_n_words: 30000
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/tvsub/vocab/en.json"
      max_n_words: 30000
  max_len:
    - 80
    - 80
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: DocNMT
  n_layers: 6
  n_head: 8
  d_word_vec: 256
  d_model: 256
  d_inner_hid: 512
  dropout: 0.1
  proj_share_weight: true
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 256
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 50
  shuffle: true
  use_bucket: true
  batch_size: 1024
  batching_key: "tokens"
  update_cycle: 4
  valid_batch_size: 128
  disp_freq: 1000
  save_freq: 1000
  num_kept_checkpoints: 1
  loss_valid_freq: 1000
  bleu_valid_freq: 1000
  bleu_valid_batch_size: 64
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 150
    beam_size: 5
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 50